# Generated by Django 3.0.7 on 2020-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMER', '0002_customer_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
